ppi_site_prediction:
  _target_: proteinworkshop.tasks.ppi_site_prediction.BindingSiteTransform
  radius: 3.5 #Maximum distance between chains to be considered as interacting
  ca_only: False #Whether to use only the alpha carbon atoms for determining interactions
