_target_: proteinworkshop.features.factory.ProteinFeaturiser
representation: CA
scalar_node_features:
  - amino_acid_one_hot
  #- dihedrals
  #- alpha
  #- kappa
vector_node_features: []
edge_types:
  - knn_10
  #- eps_8
scalar_edge_features:
  - edge_distance
  #- edge_type_one_hot
vector_edge_features: []
