_target_: proteinworkshop.features.factory.ProteinFeaturiser
representation: CA
scalar_node_features:
  - amino_acid_one_hot
  - sequence_positional_encoding
  - alpha
  - kappa
  - dihedrals
vector_node_features: []
edge_types:
  - knn_16
scalar_edge_features:
  - edge_distance
vector_edge_features: []
