program: proteinworkshop/train.py
method: grid
name: ptm_site_prediction_baseline
metric: # Does not matter, as we are using sweep to run the experiment.
  goal: minimize
  name: val/loss/total

parameters:
  task:
    values: [multilabel_node_classification]

  dataset:
    values: [ptm]

  encoder:
    values: [schnet, dimenet_plus_plus, gear_net_edge, egnn, gcpnet]

  optimiser.optimizer.lr:
    values: [0.0001]

  features:
    values: [ca_base, ca_seq, ca_angles, ca_bb, ca_sc]

  scheduler:
    value: plateau

  extras.enforce_tags:
    value: False

  +aux_task:
    values: [none, nn_sequence, nn_structure_torsion, nn_structure_r3]

  trainer.max_epochs:
    value: 150

  test:
    value: True

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
