program: proteinworkshop/train.py
method: grid
name: ppi_site_prediction_baseline
metric: # Does not matter, as we are using sweep to run the experiment.
  goal: minimize
  name: val/loss/total

parameters:
  task:
    values: [ppi_site_prediction]

  dataset:
    values: [masif_site]

  encoder:
    values: [schnet, gear_net_edge, egnn, gcpnet, tfn, mace]

  dataset.datamodule.batch_size:
    value: 16

  features:
    values: [ca_base, ca_seq, ca_angles, ca_bb, ca_sc]

  scheduler:
    value: plateau

  extras.enforce_tags:
    value: False

  +aux_task:
    values: [none, nn_sequence, nn_structure_r3]

  trainer.max_epochs:
    value: 300

  test:
    value: True

  logger:
    value: wandb

  name:
    value: "${hydra:runtime.choices.encoder}_${hydra:runtime.choices.features}_${hydra:runtime.choices.aux_task}"

  optimiser.optimizer.lr:
    value: ${hparams.hparams.lr}

  decoder.node_label.dropout:
    value: ${hparams.hparams.decoder_dropout}

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
