defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - learning_rate_monitor.yaml
  - stop_on_nan.yaml
  - _self_

model_checkpoint:
  dirpath: ${env.paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1
