# https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/common/callbacks/ema.py

# Maintains an exponential moving average (EMA) of model weights.
# Look at the above link for more detailed information regarding the original implementation.
ema:
  _target_: proteinworkshop.utils.EMA
  decay: 0.9999 # weight decay factor for the EMA
  apply_ema_every_n_steps: 1 # after how many steps to apply the EMA
  start_step: 0 # when to start the EMA
  save_ema_weights_in_callback_state: true # whether to store the EMA weights in the corresponding `LightningModule`'s `callback` state
  evaluate_ema_weights_instead: true # whether to perform e.g., validation or testing using the EMA weights instead of the original weights
