# @package _global_

# For general info:
#   c.f. https://hydra.cc/docs/plugins/submitit_launcher/#internaldocs-banner
# For documentation on submitit launcher variables:
#   c.f. https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py
# For running use:
#   python myscript.py myparam="bla" +launcher=csd3_ampere --multirun

# @package _global_
defaults:
  - override /trainer: gpu
  - override /hydra/launcher: submitit_slurm # NOTE: Requires `pip install submitit`

hydra:
  launcher:
    timeout_min: 120 # time in minutes
    name: ${hydra.job.name}
    mem_gb: 64 # memory in GB
    nodes: 1
    partition: pascal
    account: LIO-SL3-GPU
    gres: gpu:1
    cpus_per_task: ${dataset.datamodule.num_workers}
    #    gpus_per_node: 4
    #    tasks_per_node: 4
    #    mem_per_gpu: null
    #    mem_per_cpu: null
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    setup:
      - ". /etc/profile.d/modules.sh                # Leave this line (enables the module command)"
      - "module load rhel8/default-amp              # REQUIRED - loads the basic environment]"
#    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
