_target_: "proteinworkshop.models.graph_encoders.egnn.EGNNModel"
num_layers: 6 # Number of message passing layers
emb_dim: 512 # Dimension of the node embeddings
activation: relu # Activation function to use
norm: layer # Normalisation layer to use
aggr: "sum" # Aggregation function to use
pool: "sum" # Pooling operation to use
residual: True # Whether to use residual connections
