# @package _global_

defaults:
  - override /metrics:
      - accuracy
      - f1_score
      - f1_max
      - rocauc
      - auprc
  - override /decoder:
      - graph_label
  - override /transforms:
    - remove_missing_ca
    - multihot_label_encoding

metrics:
  accuracy:
    num_labels: ${dataset.num_classes}
  f1_score:
    num_labels: ${dataset.num_classes}
  rocauc:
    num_labels: ${dataset.num_classes}


callbacks:
  early_stopping:
    monitor: val/graph_label/accuracy
    mode: "max"
  model_checkpoint:
    monitor: val/graph_label/accuracy
    mode: "max"

task:
  task: "classification"
  classification_type: "multilabel"
  metric_average: "micro"

  losses:
    graph_label: bce
  label_smoothing: 0.0

  output:
    - "graph_label"
  supervise_on:
    - "graph_label"
