# @package _global_

# === 1. Set config parameters ===
name: "" # default name for the experiment, "" means logger (eg. wandb) will generate a unique name
seed: 52 # seed for random number generators in pytorch, numpy and python.random (as well as in UMAP)
num_workers: 16 # number of subprocesses to use for data loading.

# === 2. Specify defaults here. Defaults will be overwritten by equivalently named options in this file ===
defaults:
  - env: default
  - dataset: fold_superfamily
  - features: ca_bb
  - encoder: gcpnet
  - decoder: default
  - transforms: none
  - callbacks: default
  - extras: default
  - hydra: default
  - metrics: default
  - task: multiclass_graph_classification
  - finetune: default
  - debug: null
  - _self_ # see: https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/. Adding _self_ at bottom means values in this file override defaults.

task_name: "visualise"

compile: True

# simply provide checkpoint path and plot filepath to embed dataset and plot its UMAP embeddings
ckpt_path: null # path to checkpoint to load
plot_filepath: null # path to which to save embeddings plot
use_cuda_device: True # if True, use an available CUDA device for embedding generation
cuda_device_index: 0 # if CUDA devices are targeted and available, which available CUDA device to use for embedding generation

visualise:
  label: "graph_label" # name of the model output with which to annotate nodes in the embedding plot
  split: ["train", "val", "test"]