datamodule:
  _target_: "proteinworkshop.datasets.astral.AstralDataModule"
  path: ${env.paths.data}/Astral/ # Directory where the dataset is stored
  release: "2.08" # Version of ASTRAL to use
  identity: "95" # Percent identity clustering threshold to use
  batch_size: 32 # Batch size for dataloader
  pin_memory: True # Pin memory for dataloader
  num_workers: 4 # Number of workers for dataloader
  dataset_fraction: 1.0 # Fraction of dataset to use
  transforms: ${transforms} # Transforms to apply to dataset examples
  overwrite: False # Whether to overwrite cached dataset example files
  train_val_test: [0.8, 0.1, 0.1] # Cross-validation ratios to use for train, val, and test splits
num_classes: null # Number of classes
