datamodule:
  _target_: proteinworkshop.datasets.dummy_datamodule.DummyDataModule
  path: ${env.paths.data}/dummy/ # Directory where the dataset is stored
  pdb_dir: ${env.paths.data}/pdb/ # Directory where raw PDB/mmtf files are stored
  batch_size: 8 # Batch size for dataloader
  pin_memory: True # Pin memory for dataloader
  num_workers: 8 # Number of workers for dataloader
  obsolete_strategy: "drop"
  format: "mmtf.gz" # Format of the raw PDB/MMTF files
  transforms: ${transforms}
  overwrite: True

num_classes: 2 # Number of classes in the dataset