datamodule:
  _target_: "proteinworkshop.datasets.fold_classification.FoldClassificationDataModule"
  path: ${env.paths.data}/FoldClassification/ # Directory where the dataset is stored
  split: "family" # Level of fold classification to perform (`family`, `superfamily`, or `fold`)
  batch_size: 32 # Batch size for dataloader
  pin_memory: True # Pin memory for dataloader
  num_workers: 4 # Number of workers for dataloader
  dataset_fraction: 1.0 # Fraction of dataset to use
  shuffle_labels: False # Whether to shuffle labels for permutation testing
  transforms: ${transforms} # Transforms to apply to dataset examples
  overwrite: False # Whether to overwrite existing dataset files
num_classes: 1195 # Number of classes
