datamodule:
  _target_: graphein.ml.datasets.foldcomp_dataset.FoldCompLightningDataModule
  data_dir: ${env.paths.data}/highquality_clust30/
  database: "highquality_clust30"
  batch_size: 32
  num_workers: 4

  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

  pin_memory: True
  use_graphein: True
  transform: ${transforms}

dataset_name: "highquality_clust30"
num_classes: None # number of classes
