datamodule:
  _target_: proteinworkshop.datasets.metal_3d.Metal3DDataModule
  path: ${env.paths.data}/Metal3D/ # Directory where the dataset is stored
  pdb_dir: ${env.paths.data}/pdb/ # Directory where raw PDB/mmtf files are stored
  format: "mmtf" # Format of the raw PDB/MMTF files
  in_memory: False # Whether to load the whole dataset into memory
  batch_size: 32 # Batch size for dataloader
  pin_memory: True # Pin memory for dataloader
  num_workers: 8 # Number of workers for dataloader
  transforms: ${transforms}
  obsolete_strategy: "drop"  # Or replace
  overwrite: False
num_classes: 2
