pos:
  _target_: proteinworkshop.models.decoders.mlp_decoder.PositionDecoder
  num_message_layers: 2
  message_hidden_dim: 128
  message_activation: "relu"
  message_dropout: 0.0
  message_skip: False
  num_distance_layers: 1
  distance_hidden_dim: 128
  distance_activation: "relu"
  distance_dropout: 0.0
  distance_skip: False
